tutorTool/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    # path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
]

tutorTool/mytutor/urls.py
from django.urls import path
from . import views


app_name = "mytutor"

urlpatterns = [
    path('user_request/<int:pk>', views.handle_request, name='user_request'),
    path('response/<int:pk>', views.ResponseDetail.as_view(), name='response'),
    path('myrequests', views.ResponseList.as_view(), name='requests'),
    path("delete/<int:pk>/", views.delete_response, name="delete"),
]

tutorTool/tutorproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('mytutor/', include('mytutor.urls', namespace='tutor')),
]

tutorTool/accounts/models.py
from django.db import models
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

tutorTool/mytutor/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.urls import reverse

User = get_user_model()


class Response(models.Model):
    user = models.ForeignKey(User, related_name='responses', on_delete=models.SET_NULL, null=True)
    input = models.TextField(blank=True, default='', max_length=3000)
    text = models.TextField(blank=True, default='', max_length=3000)
    request = models.CharField(blank=True, default='', max_length=10)
    created_dt = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.request

    def save(self, *args, **kwargs):
        self.created_dt = timezone.now()
        # self.save()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tutor:tutor_detail', kwargs={'pk': self.id},)

    class Meta:
        ordering = ['-created_dt']

tutorTool/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

tutorTool/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

tutorTool/mytutor/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView
from .models import Response
from .utils import get_gpt_response

User = get_user_model()


@login_required()
def handle_request(request, pk):
    new_response = Response()
    new_response.user = request.user

    if request.method == 'POST':
        if pk == 1:
            new_response.request = "Study schedule"
            subjects = request.POST.get('input')
            new_response.input = f"Create a weekly study schedule for me including the following subjects: {subjects}. Provide your response in html friendly format"
        elif pk == 2:
            person = request.POST.get('input')
            new_response.request = "Motivation from " + person
            new_response.input = f"Give me some tough love motivation to study as posing as {person}. Provide your response in html friendly format"
        elif pk == 3:

            topic = request.POST.get('input')
            new_response.request = topic + " quiz"
            new_response.input = f"Create a 15 question quiz based on the following topic: {topic}. Include the answers further down in youb resposne so I hahve to scroll down to see them. Provide your response in html friendly format"
        else:
            return render(request, 'mytutor/tutor_index.html')


        new_response.text = get_gpt_response(new_response.input)
        new_response.save()

        return render(request, 'mytutor/response_detail.html', {'response' : new_response})
    else:
        return render(request, 'mytutor/tutor_index.html')


class ResponseDetail(LoginRequiredMixin, generic.DetailView):
    model = Response


class ResponseList(LoginRequiredMixin, generic.ListView):
    model = Response


@login_required()
def delete_response(request, pk):
    response = get_object_or_404(Response, pk=pk)
    response.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

tutorTool/tutorproject/views.py
from django.views.generic import TemplateView



class HomePage(TemplateView):
    template_name = 'index.html'

tutorTool/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-secondary">Login</button>

  </form>
</div>
{% endblock %}

tutorTool/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-default btn-outline-secondary" value="Sign up">
    </form>
</div>


{% endblock %}

tutorTool/mytutor/templates/mytutor/response_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="jumbotron container">
    <h2>{{response.request| capfirst}}</h2><br>
    <h4>{{response.text |safe}}</h4>
   </div>
{% endblock %}

tutorTool/mytutor/templates/mytutor/response_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<br>
 <div align="center" class="container">

	{% for response in object_list %}
     <div class="col-md-8">

        <div>
            <a class="response_links" href="{% url 'mytutor:response' pk=response.id  %}">{{ response.request }}</a>

            <a class="delete_icon" href="{% url 'mytutor:delete' pk=response.id  %}"><i class="bi bi-trash3"></i></a>
        </div>


     </div>
     <p> {{ response.created_dt }} </p>
	{% endfor %}



</div>
{% endblock %}

tutorTool/mytutor/templates/mytutor/tutor_index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<br>
 <div align="center" class="container" id="doc-form-wrapper">
   <div class="jumbotron selection_panel" id="request_selection_panel">
    <h2>What would like me to help you with?</h2>
    <button onclick="showInput('1')" class="btn btn-outline-secondary w-120">Create a study schedule</button>
     <button onclick="showInput('2')" class="btn btn-outline-secondary w-120">I NEED SOME MOTIVATION</button>
    <button onclick="showInput('3')" class="btn btn-outline-secondary w-120">Create a quiz</button>
   </div>
   <div align="center" class="container">
     <br><br><hr>
     <form id="input_form" method="POST" style="display: none;">
        {% csrf_token %}
        <input type="text" id="input" name="input">
        <button type="submit" class="btn btn-outline-secondary" id="submit_button">Submit</button>
    </form>
   </div>

</div>
    <script>
        function showInput(pk) {
            const form = document.getElementById('input_form');
            const input = document.getElementById('input');
            const submitButton = document.getElementById('submit_button');

            form.style.display = 'block';
            form.action = `${pk}`;

            if (pk === '1') {
                input.placeholder = 'What subjects would you like to include?';
            } else if (pk === '2') {
                input.placeholder = 'Who would you like to hear it from?';
            } else if (pk === '3') {
                input.placeholder = 'Sure, give me a topic';
            }
        }

        //function directSubmit(buttonType) {
         //   window.location.href = `/submit/${pk}/`;
        //}
    </script>
{% endblock %}

tutorTool/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html>
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<!-- Mobile Metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />

  <title>TutorTool</title>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!--        Custom CSS styling -->
   <link href="{% static 'css/style.css' %}" rel="stylesheet"/>

   <!--        Fonts -->
   <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">

  <!--        Icons -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

 </head>
<body class="base_body">

  <header class="header_section">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg custom_nav-container">
        <ul class="navbar-nav mr-auto">
          <a class="navbar-brand mynav" id="brandname" href="{% url 'home' %}">TutorTool</a>
        </ul>

          <ul class="navbar-nav ms-auto">
            {% if user.is_authenticated %}

            <li class="nav-item">
            <a class="nav-link" href="{% url 'mytutor:user_request' pk=0  %}">New Request </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'mytutor:requests' %}">My Requests</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                  <button class="nav-link" type="submit">Logout</button>
              </form>
            </li>
            {% else %}
            <li class="nav-item">
            <a id="loginbutton" class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
            </li>
            {% endif %}
          </ul>
    </nav>
  </div>
</header>

<section class=" content_section">


  {% block content %}
  {% endblock %}

</section>

tutorTool/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron selection_panel" align="center" id="getstarted_panel">
  <h1>Welcome {{ user.username}}</h1>
    <a href="{% url 'mytutor:user_request' pk=0  %}" role="button" class="btn btn-outline-secondary w-120">Get Started</a>
</div>


{% endblock %}

tutorTool/templates/logout.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container">
  <h1>Logged out</h1>

  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %} #csrf_token is very important to have as this is POST request
    <button type="submit">Logout</button>
</form>
</div>
{% endblock %}